// generated by stringer -type=ExitCode; DO NOT EDIT

package sysexits

import "fmt"

const _ExitCode_name = "ExitOk"

var _ExitCode_index = [...]uint8{6}

func (i ExitCode) String() string {
	if i < 0 || i >= ExitCode(len(_ExitCode_index)) {
		return fmt.Sprintf("ExitCode(%d)", i)
	}
	hi := _ExitCode_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ExitCode_index[i-1]
	}
	return _ExitCode_name[lo:hi]
}
